import { APP_INITIALIZER, ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import {
  LucideAngularModule,
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignLeft,
  ArrowLeft,
  ArrowRight,
  Bell,
  BookOpen,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronUp,
  CircleDot,
  ClipboardList,
  Clock,
  Download,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileImage,
  FilePlus2,
  FileText,
  Filter,
  Folder,
  FolderLock,
  FolderOpen,
  GitBranch,
  Hand,
  Image,
  Hash,
  History,
  Inbox,
  Info,
  LayoutDashboard,
  LayoutList,
  List,
  ListChecks,
  ListPlus,
  Loader,
  Lock,
  LogOut,
  Mail,
  Menu,
  Mic,
  MicOff,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Tags,
  Trash2,
  Type,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserSearch,
  Users,
  Wand2,
  Workflow,
  X
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { AuthService } from './core/services/auth.service';

/**
 * Rehydrates the AuthService from localStorage before the router runs so
 * guards see a valid session on page reload.
 */
function sessionInitializer(auth: AuthService): () => void {
  return () => auth.restoreSession();
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    {
      provide: APP_INITIALIZER,
      useFactory: sessionInitializer,
      deps: [AuthService],
      multi: true
    },
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity,
        AlertCircle,
        AlertTriangle,
        AlignLeft,
        ArrowLeft,
        ArrowRight,
        Bell,
        BookOpen,
        Calendar,
        CalendarClock,
        Check,
        CheckCircle,
        CheckSquare,
        ChevronDown,
        ChevronUp,
        CircleDot,
        ClipboardList,
        Clock,
        Download,
        Eye,
        EyeOff,
        File,
        FileCode,
        FileImage,
        FilePlus2,
        FileText,
        Filter,
        Folder,
        FolderLock,
        FolderOpen,
        GitBranch,
        Hand,
        Image,
        Hash,
        History,
        Inbox,
        Info,
        LayoutDashboard,
        LayoutList,
        List,
        ListChecks,
        ListPlus,
        Loader,
        Lock,
        LogOut,
        Mail,
        Menu,
        Mic,
        MicOff,
        PanelRightClose,
        PanelRightOpen,
        Paperclip,
        Pencil,
        Play,
        Plus,
        RefreshCw,
        Rocket,
        RotateCcw,
        Save,
        Search,
        Settings,
        ShieldCheck,
        Sparkles,
        Tags,
        Trash2,
        Type,
        Upload,
        User,
        UserCheck,
        UserPlus,
        UserSearch,
        Users,
        Wand2,
        Workflow,
        X
      })
    )
  ]
};
